<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function states_form_myformid_alter(&$form, &$form_state, $form_id) {
  // Checkbox
  $form['field_destination_1']['#states'] = array(
    'visible' => array(
      ':input[name="field_checkbox[und]' => array('checked' => TRUE),
    ),
  );
  
  // Select 
  $form['field_destination_2']['#states'] = array(
    'visible' => array(
      ':input[name="field_select[und]"]' => array('value' => 'custom'),
    ),
  );
}
